In [2]:
import os, json
import tensorflow as tf
import numpy as np

from matplotlib import pyplot as plt

In [46]:
root_path = "/home/files/datasets/PF-dataset-PASCAL"
annotation_dir = os.path.join(root_path, "PF-dataset-PASCAL/Annotations")
image_dir = os.path.join(root_path, "PF-dataset-PASCAL/JPEGImages")
class_names = [name for name in os.listdir(annotation_dir) if name != '.DS_Store']

In [47]:
list_ds = tf.data.Dataset.list_files(annotation_dir+'/*/*')

In [48]:
for i in list_ds.take(1):
    print(i)

tf.Tensor(b'/home/files/datasets/PF-dataset-PASCAL/PF-dataset-PASCAL/Annotations/motorbike/2008_005893.mat', shape=(), dtype=string)


In [49]:
def get_label(path):
    label = tf.strings.split(path, '/')[-2]
    return label
def get_image_path(path):
    filename = tf.strings.split(path, '/')[-1]
    filename = tf.strings.split(filename, '.')[-2]
    image_path = tf.strings.join([image_dir, '/', filename, '.jpg'])
    return image_path
def decode_img(file_path):
    img = tf.io.read_file(file_path)  
    # convert the compressed string to a 3D uint8 tensor
    img = tf.image.decode_jpeg(img, channels=3)
    # resize the image to the desired size
    return tf.image.resize(img, [180, 180])
def process_path(path):
    label = get_label(path)
    image_path = get_image_path(path)
    img = decode_img(image_path)
    return label, img




processed_ds = list_ds.map(process_path)

for label,path in processed_ds.take(1):
    print(label, path)

tf.Tensor(b'aeroplane', shape=(), dtype=string) tf.Tensor(
[[[ 96.37038  132.37036  156.37036 ]
  [ 97.       133.       157.      ]
  [ 97.666664 133.66667  157.66667 ]
  ...
  [102.38887  138.38887  162.38887 ]
  [103.05556  139.05556  163.05556 ]
  [103.05556  139.05556  163.05556 ]]

 [[ 97.       133.       157.      ]
  [ 97.       133.       157.      ]
  [ 97.72222  133.72223  157.72223 ]
  ...
  [103.33331  139.33331  163.33331 ]
  [104.       140.       164.      ]
  [104.       140.       164.      ]]

 [[ 97.       133.       157.      ]
  [ 97.27778  133.27777  157.27777 ]
  [ 98.18519  134.18518  158.18518 ]
  ...
  [103.33331  139.33331  163.33331 ]
  [104.       140.       164.      ]
  [104.       140.       164.      ]]

 ...

 [[124.72223  157.72223  176.72223 ]
  [125.       158.       177.      ]
  [124.333336 157.33333  176.33333 ]
  ...
  [130.09265  163.09265  180.09265 ]
  [128.27777  161.27777  178.27777 ]
  [128.27777  161.27777  178.27777 ]]

 [[125.       1

In [53]:
np.min(path)

0.0

In [45]:
!ls /home/files/datasets/PF-dataset-PASCAL

PF-dataset-PASCAL  __MACOSX


In [29]:
filename = tf.strings.split(i, '/')

In [24]:
tf.strings.join([image_dir, filename])

<tf.Tensor: shape=(), dtype=string, numpy=b'/home/files/datasets/PF-dataset-PASCAL/JPEGImages2009_005103.mat'>

In [31]:
filename[-2]

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [33]:
filename[-2] == class_names

<tf.Tensor: shape=(20,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])>

In [34]:
tf.argmax(filename[-2] == class_names)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [35]:
len(list_ds)

1351